apiVersion: v1
baseDomain: example.com
metadata:
  name: cluster-id
networking:
  machineCIDR: "10.0.0.0/24"
platform:
  vsphere:
    vCenter: vcsa67.example.com
    username: "administrator@vsphere.local"
    password: "password"
    datacenter: Boston
    defaultDatastore: datastore
pullsecret: 'pull'
sshKey: 'ssh-key' 
