cluster_id = "cluster-id"
cluster_domain = "cluster.example.com"
base_domain = "example.com"
vsphere_server = "vcsa.example.com"
vsphere_user = "administrator@vsphere.local"
vsphere_password = "password"
vsphere_cluster = "cluster"
vsphere_datacenter = "Boston"
vsphere_datastore = "datastore"
vm_template = "rhcos"
machine_cidr = "10.0.0.0/24"
bootstrap_ignition_path = "${path.module}/bootstrap.ign"
control_plane_ignition_path = "${path.module}/master.ign"
compute_ignition_path = "${path.module}/worker.ign"
control_plane_count = 3
compute_count = 3
bootstrap_ip = "10.0.0.231"
control_plane_ips = ["10.0.0.232", "10.0.0.233", "10.0.0.234"]
compute_ips = ["10.0.0.235", "10.0.0.236", "10.0.0.237"]
